baseURL = "https://ottawa-math-competition.github.io/website/"
languageCode = "en-us"
title = "Ottawa Team Math Competition"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Ottawa Team Math Competition (OTMaC)"

[params]
author = "Ottawa Team  Math Competition (OTMaC)"
description = "Anubis is a simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false
mathjax = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

# [[params.social]]
# id = "docs"
# url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[[params.social]]
id = "email"
name = "hello@otmac.ca"

[menu]

[[menu.main]]
identifier = "details"
name = "Details"
url = "/details/"
weight = 1

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[markup.goldmark.renderer]
unsafe = true
