baseURL = "localhost:1313"
languageCode = "en-us"
title = "OTTAWA-CARLETON MATH COMPETITION"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Ottawa-Carleton Math Competition"

[params]
author = "Ottawa-Carleton Math Competition"
description = "Anubis is a simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false
mathjax = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

# [[params.social]]
# id = "docs"
# url = "https://gohugo.io/documentation/"

# [[params.social]]
# id = "github"
# url = "https://github.com/mitrichius/hugo-theme-anubis"

[menu]

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 1

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[markup.goldmark.renderer]
unsafe = true
